# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  - 3.8

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
    - sudo apt-get update
    - sudo apt-get install curl
install: pip install -U -r requirements_dev.txt

# Command to run tests, e.g. python setup.py test
script: nosetests --with-coverage --cover-package=rsi
after_success:
    - coveralls
